### PR TITLE
Prepping for GF onboarding

### PR DESCRIPTION
**Pull request by aaronbell**
Hi! I've updated the source. :) 

- replaced the build system with makefile-driven implementation per GF template
- cleared unicode from softhyphen
- removed GPOS data from legacy marks
- updated / cleaned up font metadata and font info
- bumped version to 1.00

LMK if you have any concerns or questions about these modifications.

### CODE REVIEW

**Comment by lxgw** [comment]
Thanks for your efforts to board this font on Google Fonts, though I have reviewed the request and left some comments.

**Comment by aaronbell** [comment]
Thanks! I haven't seen any comments come through yet, but look forward to your thoughts :).

**Comment by lxgw** [comment]
1. ​The description is incorrect. It should be a description of LXGW Marker Gothic instead of UoqMunThenKhung. (in `documentation/DESCRIPTION.en_us.html`)
2. Both sample.py and sample.png may be useless for this project and could be removed from this repo. (in `documentation` folder)
3. It seems that only the zip file is uploaded onto the release. Why not update the font file as well? (in `.github/workflows/build.yaml`)

**Comment by aaronbell** [comment]
@lxgw Thanks! I've updated the `DESCRIPTION` file and removed the sample stuff (plus related bits and bobs). 

For the workflow question, Google recommends not keeping the TTF files in the repository, and instead relying on the build system / release system to store fonts for release. So the build workflow will automatically produce a zip file of the artefacts (the compiled fonts) on the `Actions` tab. It is then assumed that, when one is ready to cut a new release, that one will manually go and assign a tag to the latest release and attach the artifact zip folder to the release. Does that make sense?

**Comment by lxgw** [comment]
I uploaded the TTF font inside the repo because the guideline ( https://googlefonts.github.io/gf-guide/upstream.html ) suggested us to do so. I would like to keep the TTF font in the repo as stated in the guideline, which also ensure backwards-compatibility. Also, I would prefer to upload both the TTF and the ZIP file when release.

**Comment by aaronbell** [comment]
Thanks! The guidance is currently in a state of flux on the matter of the font's inclusion. Anyway, I have some additional modifications to do on this, so will close for the time being until I'm ready :).

**Pull request closed without merging**
